Team8CA/Models/OrderHistory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Team8CA.DataAccess;

namespace Team8CA.Models
{       
    public class OrderHistory

    {/*
        public List<ShoppingCart> GetOrderHistory(int customerId)
        {
            var carts = Order.Where(o => o.CustomerId == customerId && o.IsCheckOut).ToList(); 
            return carts;
        } */

       
    }
}

Team8CA/Controllers/CreateReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using Team8CA.DataAccess;
using Team8CA.Models;
//using Team8CA.Services;

namespace Team8CA.Controllers
{
    public class CreateReviewController : Controller
    {
        protected AppDbContext db;
        public CreateReviewController(AppDbContext db)
        {
            this.db = db;
        }
        public IActionResult Index(int id)
        {  
            Products product = db.Products.First(p => p.ProductId == id);

            ViewData["firstname"] = Request.Cookies["firstname"];
            string sessionid = Request.Cookies["sessionId"];
            ViewData["sessionId"] = sessionid;
            string customerId = Request.Cookies["customerId"];
            ViewData["customerid"] = customerId;
            List<ShoppingCartItem> shoppingcart = db.ShoppingCartItem.Where(x => x.ShoppingCartId == customerId).ToList();
            List<ShoppingCartItem> shoppingcartNull = db.ShoppingCartItem.Where(x => x.ShoppingCartId == "0").ToList();
            if (sessionid != null)
            {
                ViewData["cartcount"] = shoppingcart.Count;
            }
            else
            {
                ViewData["cartcount"] = shoppingcartNull.Count;
            }
            ViewData["product"] = product;

            return View();
        }

        [HttpPost]
        public IActionResult Create(int rating, string details, int productId, int?orderId)
        {
            if (!ModelState.IsValid)
                return View();
            Models.Review review = new Models.Review(productId, Request.Cookies["firstname"], rating, details, DateTime.Now);
            string customerId = Request.Cookies["customerId"];
            review.CustomerId = customerId;
            Products p = db.Products.FirstOrDefault(p => p.ProductId == productId);
            if (orderId == null)
            {
                Models.Order OrderwithProduct = db.Order
                    .FirstOrDefault(o => o.CustomerId == customerId && o.OrderDetails.Any(d => d.ProductId == p.ProductId && d.reviewed != true) == true);
                review.OrderId = OrderwithProduct.OrderId;

            }
            else
            {
                review.OrderId = (int)orderId;
            }

            db.OrderDetails.FirstOrDefault(o => o.OrderId == review.OrderId && o.ProductId == productId).reviewed = true;
            db.Reviews.Add(review);
            db.SaveChanges();

            return RedirectToAction("ProductDetailPage","Gallery", new { id = productId });
        }


    }
}

Team8CA/Controllers/GalleryController.cs
using System;
using System.Web;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;
//using X.PagedList.Mvc;
using X.PagedList.Mvc.Core;
using Team8CA.DataAccess;
using Team8CA.Models;
//using Team8CA.Services;

namespace Team8CA.Controllers
{
    public class GalleryController : Controller
    {
        protected AppDbContext db;

        public IActionResult Index(int? page)                                    
        {                                                                      
            List<Products> product = db.Products.ToList();          
            ViewData["product"] = product;

            var pageNumber = page ?? 1; 
            var onePageOfProducts = product.ToPagedList(pageNumber, 6);
            ViewData["OnePageOfProducts"] = onePageOfProducts;

            ViewData["username"] = Request.Cookies["username"];
            ViewData["firstname"] = Request.Cookies["firstname"];
            string sessionid = Request.Cookies["sessionId"];
            ViewData["sessionId"] = sessionid;
            string customerId = Request.Cookies["customerId"];
            ViewData["customerid"] = customerId;
            List<ShoppingCartItem> shoppingcart = db.ShoppingCartItem.Where(x => x.ShoppingCartId == customerId).ToList();
            List<ShoppingCartItem> shoppingcartNull = db.ShoppingCartItem.Where(x => x.ShoppingCartId == "0").ToList();
            if (sessionid != null)
            {
                ViewData["cartcount"] = shoppingcart.Count;
            }
            else
            {
                ViewData["cartcount"] = shoppingcartNull.Count;
            }

            return View();
        }

        public IActionResult AntivirusAndSecurity()
        {
            ViewData["username"] = Request.Cookies["username"];
            ViewData["firstname"] = Request.Cookies["firstname"];
            string sessionid = Request.Cookies["sessionId"];
            ViewData["sessionId"] = sessionid;
            string customerId = Request.Cookies["customerId"];
            ViewData["customerid"] = customerId;
            List<ShoppingCartItem> shoppingcart = db.ShoppingCartItem.Where(x => x.ShoppingCartId == customerId).ToList();
            List<ShoppingCartItem> shoppingcartNull = db.ShoppingCartItem.Where(x => x.ShoppingCartId == "0").ToList();
            if (sessionid != null)
            {
                ViewData["cartcount"] = shoppingcart.Count;
            }
            else
            {
                ViewData["cartcount"] = shoppingcartNull.Count;
            }
            List<Products> product = db.Products.Where(p => (p.ProductCategory == "AntivirusandSecurity")).ToList();
            ViewData["product"] = product;

            ViewData["firstname"] = Request.Cookies["firstname"];
            ViewData["sessionId"] = Request.Cookies["sessionId"];
            return View();
        }

        public IActionResult BusinessAndOffice()
        {
            ViewData["username"] = Request.Cookies["username"];
            ViewData["firstname"] = Request.Cookies["firstname"];
            string sessionid = Request.Cookies["sessionId"];
            ViewData["sessionId"] = sessionid;
            string customerId = Request.Cookies["customerId"];
            ViewData["customerid"] = customerId;
            List<ShoppingCartItem> shoppingcart = db.ShoppingCartItem.Where(x => x.ShoppingCartId == customerId).ToList();
            List<ShoppingCartItem> shoppingcartNull = db.ShoppingCartItem.Where(x => x.ShoppingCartId == "0").ToList();
            if (sessionid != null)
            {
                ViewData["cartcount"] = shoppingcart.Count;
            }
            else
            {
                ViewData["cartcount"] = shoppingcartNull.Count;
            }
            List<Products> product = db.Products.Where(p => (p.ProductCategory == "BusinessAndOffice")).ToList();
            ViewData["product"] = product;

            ViewData["firstname"] = Request.Cookies["firstname"];
            ViewData["sessionId"] = Request.Cookies["sessionId"];
            return View();
        }
        public IActionResult DesignAndIllustration()
        {
            ViewData["username"] = Request.Cookies["username"];
            ViewData["firstname"] = Request.Cookies["firstname"];
            string sessionid = Request.Cookies["sessionId"];
            ViewData["sessionId"] = sessionid;
            string customerId = Request.Cookies["customerId"];
            ViewData["customerid"] = customerId;
            List<ShoppingCartItem> shoppingcart = db.ShoppingCartItem.Where(x => x.ShoppingCartId == customerId).ToList();
            List<ShoppingCartItem> shoppingcartNull = db.ShoppingCartItem.Where(x => x.ShoppingCartId == "0").ToList();
            if (sessionid != null)
            {
                ViewData["cartcount"] = shoppingcart.Count;
            }
            else
            {
                ViewData["cartcount"] = shoppingcartNull.Count;
            }
            List<Products> product = db.Products.Where(p => (p.ProductCategory == "DesignAndIllustration")).ToList();
            ViewData["product"] = product;

            ViewData["firstname"] = Request.Cookies["firstname"];
            ViewData["sessionId"] = Request.Cookies["sessionId"];
            return View();
        }

        public GalleryController(AppDbContext db)
        {
            this.db = db;
        }
        public List<Products> GetProducts(string keyword)
        {
            List<Products> products = db.Products.ToList();
            {
                if (keyword == "" || keyword == null)
                {
                    return db.Products.ToList();
                }

                return db.Products.Where(p =>
                        p.ProductName.ToLower().Contains(keyword.ToLower()) ||
                        p.ProductDescription.ToLower().Contains(keyword.ToLower()))
                    .ToList();
            }
        }

        [HttpPost]
        public IActionResult Search(string keyword = "")
        {
            List<Products> product = GetProducts(keyword);
            ViewBag.keyword = keyword;
            ViewData["product"] = keyword;
            return View("Index");
        }

        //Link to productDetailPage
        public IActionResult ProductDetailPage(int id)
        {
            ViewData["username"] = Request.Cookies["username"];
            ViewData["firstname"] = Request.Cookies["firstname"];
            string sessionid = Request.Cookies["sessionId"];
            ViewData["sessionId"] = sessionid;
            string customerId = Request.Cookies["customerId"];
            ViewData["customerid"] = customerId;
            List<ShoppingCartItem> shoppingcart = db.ShoppingCartItem.Where(x => x.ShoppingCartId == customerId).ToList();
            List<ShoppingCartItem> shoppingcartNull = db.ShoppingCartItem.Where(x => x.ShoppingCartId == "0").ToList();
            if (sessionid != null)
            {
                ViewData["cartcount"] = shoppingcart.Count;
            }
            else
            {
                ViewData["cartcount"] = shoppingcartNull.Count;
            }

            Products product = db.Products.FirstOrDefault(p => p.ProductId == id);
            List<Products> similarProducts = db.Products.Where(p => 
                                               (p.ProductCategory == product.ProductCategory) && (p!=product))
                                                .ToList();
            
            var reviews = db.Reviews.Where(r => r.ProductID == product.ProductId).ToList();
            double averageRating = reviews.Average(r=>r.StarRating);
            ViewData["reviews"] = reviews;
            ViewData["averageRating"] = averageRating;
            ViewData["product"] = product;
            ViewData["similarProducts"] = similarProducts;
            ViewData["firstname"] = Request.Cookies["firstname"];
            ViewData["sessionId"] = Request.Cookies["sessionId"];

            sessionid = Request.Cookies["sessionId"];
            ViewData["sessionId"] = sessionid;
            customerId = Request.Cookies["customerId"];
            ViewData["customerid"] = customerId;
            shoppingcart = db.ShoppingCartItem.Where(x => x.ShoppingCartId == customerId).ToList();
            shoppingcartNull = db.ShoppingCartItem.Where(x => x.ShoppingCartId == "0").ToList();

            if (sessionid != null)
            {
                ViewData["cartcount"] = shoppingcart.Count;
            }
            else
            {
                ViewData["cartcount"] = shoppingcartNull.Count;
            }

            bool boughtThis = false;
            List<Order> customerOrders = db.Order.Where(o => o.CustomerId == customerId).ToList();
            foreach (Order order in customerOrders) 
            {
                if (order.OrderDetails.Any(o => o.ProductId == id)) 
                {
                    boughtThis = true;
                    break;
                }
            }
            ViewData["boughtThis"] = boughtThis;

            bool reviewedThis = db.Order.Any(o => o.CustomerId == customerId && o.OrderDetails.Any(o => o.reviewed != true && o.ProductId == id));
            ViewData["reviewedThis"] = !reviewedThis;

            return View();

        }

        public IActionResult RemoveReview(int id)
        {
            string customerid = Request.Cookies["customerId"];
            ViewData["customerid"] = customerid;
            string sessionid = Request.Cookies["sessionId"];
            if (sessionid == null)
            {
                customerid = "0";
            }
            var reviewselected = db.Reviews.FirstOrDefault(r => r.ProductID == id && r.CustomerId == customerid);
            if (reviewselected != null)
            {
                db.Reviews.Remove(reviewselected);

Team8CA/Controllers/OrderHistoryController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Team8CA.DataAccess;
using Team8CA.Models;


namespace Team8CA.Controllers
{
    public class OrderHistoryController : Controller
    {


        private readonly AppDbContext db;
        private readonly ShoppingCart shoppingcart;


        public OrderHistoryController(AppDbContext db, ShoppingCart shoppingcart)
        {
            this.db = db;
            this.shoppingcart = shoppingcart;
        }

        public IActionResult Index()
        {
            string customerId = Request.Cookies["customerId"];
            List<Order> orders = db.Order.Where(o => o.CustomerId == customerId).ToList();

            ViewData["order"] = orders;

            ViewData["firstname"] = Request.Cookies["firstname"];
            string sessionid = Request.Cookies["sessionId"];
            ViewData["sessionId"] = sessionid;

            ViewData["customerid"] = customerId;
            List<ShoppingCartItem> shoppingcart = db.ShoppingCartItem.Where(x => x.ShoppingCartId == customerId).ToList();
            List<ShoppingCartItem> shoppingcartNull = db.ShoppingCartItem.Where(x => x.ShoppingCartId == "0").ToList();
            if (sessionid != null)
            {
                ViewData["cartcount"] = shoppingcart.Count;
            }
            else
            {
                ViewData["cartcount"] = shoppingcartNull.Count;
            }
            return View();
        }
        public IActionResult RecentOrder(int orderId)
        {
            Order order = db.Order.First(x => x.OrderId == orderId);
            order.OrderDetails = db.OrderDetails.Where(x => x.OrderId == orderId).ToList();
            foreach (var o in order.OrderDetails)
            {
                o.ActivationCodes = db.ActivationCodes.Where(x => x.OrderId == orderId).ToList();
            }

            string customerId = Request.Cookies["customerId"];
            List<Order> orders = db.Order.Where(o => o.CustomerId == customerId).ToList();

            ViewData["order"] = orders;

            ViewData["firstname"] = Request.Cookies["firstname"];
            string sessionid = Request.Cookies["sessionId"];
            ViewData["sessionId"] = sessionid;
            ViewData["customerid"] = customerId;
            List<Review> cutsomerReviews = db.Reviews.Where(r => r.CustomerId == customerId).ToList();
            List<ShoppingCartItem> shoppingcart = db.ShoppingCartItem.Where(x => x.ShoppingCartId == customerId).ToList();
            List<ShoppingCartItem> shoppingcartNull = db.ShoppingCartItem.Where(x => x.ShoppingCartId == "0").ToList();
            if (sessionid != null)
            {
                ViewData["cartcount"] = shoppingcart.Count;
            }
            else
            {
                ViewData["cartcount"] = shoppingcartNull.Count;
            }

            List<Review> customerReviews = db.Reviews.Where(r => r.CustomerId == customerId).ToList();
            ViewData["customerReviews"] = customerReviews;

            return View(order);
        }
    }
}

Team8CA/Views/OrderHistory/Index.cshtml
@{
    ViewData["Title"] = "OrderHistory";
    List<Order> orders = (List<Order>)ViewData["order"];
    int ordercount = orders.Count;
}
<style>
    #customers {
        border-collapse: collapse;
        width: 90%;
        margin-left: auto;
        margin-right: auto;
        table-layout: auto;
        border: 1px solid lightgray;
    }

        #customers td, #customers th {
            padding: 12px;
            padding-bottom: 12px;
            text-align: center;
            border-bottom: 1px solid lightgray;
        }

        #customers tr:hover {
            background-color: #ddd;
        }

        #customers th {
            padding-top: 12px;
            padding-bottom: 12px;
            background-color: #343a40;
            color: white;
        }
</style>

@if (ordercount > 0)
{
    <body>        
        <table id="customers">
            <thead>
                <tr>
                    <th>OrderId</th>
                    <th>Price</th>
                    <th>Ordered Date</th>
                    <th>Details</th>
                </tr>
            </thead>
            @{foreach (Order order in orders)

                {
                    <tr>
                        <td>@order.OrderId</td>
                        <td>$@order.OrderTotal</td>
                        <td>@order.OrderDate</td>
                        <td>
                            <a href=@("/OrderHistory/RecentOrder?OrderId="+@order.OrderId)>View Order Details</a>
                        </td>
                    </tr>
                }
            }
        </table>        
    </body>
}
else
{
    <div class="text-center">There are no orders made.</div><br>
    <div class="text-center"><a type="button" class="btn btn-primary view" asp-controller="Gallery" asp-action="Index">Continue Shopping</a></div>
}

Team8CA/Views/OrderHistory/RecentOrder.cshtml
@model Order
@{ 
    ViewData["Title"] = "RecentOrder";
    List<Review> customerReviews = (List<Review>)ViewData["customerReviews"];
}

<style>
    #customers {
        border-collapse: collapse;
        width: 90%;
        margin-left: auto;
        margin-right: auto;
        table-layout: auto;
        border: 1px solid lightgray;
    }

        #customers td, #customers th {
            padding: 10px;
            border-bottom: 1px solid lightgray;
        }

        #customers tr:hover {
            background-color: #ddd;
        }

        #customers th {
            padding-top: 12px;
            padding-bottom: 12px;
            background-color: #343a40;
            color: white;
            text-align: center;
        }
</style>

<div class="container">
<table id="customers">
    <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Unit Price</th>
        <th>Total Price</th>
        <th>Activation Code</th>
    </tr>
     @foreach (OrderDetails orders in Model.OrderDetails)
     {
            <tr>
                <td>
                    <div>
                        <img src="@orders.Product.ProductPic" style="min-width: 50px; max-width: 100px; display: inline-block">
                        <div class="pb-2 ml-3 d-inline-block font-weight-bold">@orders.Product.ProductName</div>
                        <div class="pt-2 d-lg-table-row"><small>@orders.Product.ProductDescription</small></div><br>

                        @if (customerReviews.Any(r => r.ProductID == orders.ProductId && r.OrderId == orders.OrderId))
                        {
                            <div><p class="text-muted">You have reviewed this product.</p></div>
                        }
                        else
                        {
                            <a class="btn btn-success float-right mx-2" id="leave-review" asp-controller="CreateReview" asp-action="Index" asp-route-id="@orders.Product.ProductId">Leave a Review</a>
                        }
                        <div class="mx-2">
                            <a class="btn btn-outline-info float-right " asp-controller="Gallery" asp-action="ProductDetailPage" asp-route-id="@orders.Product.ProductId">View Details</a>
                        </div>
                    </div>
                </td>
                <td><center>@orders.Quantity</center></td>
                <td><center>$@orders.Price</center></td>
                @{ 
                    double ordertotal = orders.Price * orders.Quantity;
                }
                <td><center>$@ordertotal</center></td>
                <td>
                    <select>
                     @{
                        foreach (var activationcode in orders.ActivationCodes.Where(o=>o.ProductId == orders.ProductId))
                        {
                            <option>@activationcode.ActivationCode</option>
                        }
                      }
                    </select>
                </td>
            </tr>

      } 
</table>
</div>