Team8CA/Controllers/GalleryController.cs
using System;
using System.Web;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;
//using X.PagedList.Mvc;
using X.PagedList.Mvc.Core;
using Team8CA.DataAccess;
using Team8CA.Models;
//using Team8CA.Services;

namespace Team8CA.Controllers
{
    public class GalleryController : Controller
    {
        protected AppDbContext db;

        public IActionResult Index(int? page)                                    
        {                                                                      
            List<Products> product = db.Products.ToList();          
            ViewData["product"] = product;

            var pageNumber = page ?? 1; 
            var onePageOfProducts = product.ToPagedList(pageNumber, 6);
            ViewData["OnePageOfProducts"] = onePageOfProducts;

            ViewData["username"] = Request.Cookies["username"];
            ViewData["firstname"] = Request.Cookies["firstname"];
            string sessionid = Request.Cookies["sessionId"];
            ViewData["sessionId"] = sessionid;
            string customerId = Request.Cookies["customerId"];
            ViewData["customerid"] = customerId;
            List<ShoppingCartItem> shoppingcart = db.ShoppingCartItem.Where(x => x.ShoppingCartId == customerId).ToList();
            List<ShoppingCartItem> shoppingcartNull = db.ShoppingCartItem.Where(x => x.ShoppingCartId == "0").ToList();
            if (sessionid != null)
            {
                ViewData["cartcount"] = shoppingcart.Count;
            }
            else
            {
                ViewData["cartcount"] = shoppingcartNull.Count;
            }

            return View();
        }

        public IActionResult AntivirusAndSecurity()
        {
            ViewData["username"] = Request.Cookies["username"];
            ViewData["firstname"] = Request.Cookies["firstname"];
            string sessionid = Request.Cookies["sessionId"];
            ViewData["sessionId"] = sessionid;
            string customerId = Request.Cookies["customerId"];
            ViewData["customerid"] = customerId;
            List<ShoppingCartItem> shoppingcart = db.ShoppingCartItem.Where(x => x.ShoppingCartId == customerId).ToList();
            List<ShoppingCartItem> shoppingcartNull = db.ShoppingCartItem.Where(x => x.ShoppingCartId == "0").ToList();
            if (sessionid != null)
            {
                ViewData["cartcount"] = shoppingcart.Count;
            }
            else
            {
                ViewData["cartcount"] = shoppingcartNull.Count;
            }
            List<Products> product = db.Products.Where(p => (p.ProductCategory == "AntivirusandSecurity")).ToList();
            ViewData["product"] = product;

            ViewData["firstname"] = Request.Cookies["firstname"];
            ViewData["sessionId"] = Request.Cookies["sessionId"];
            return View();
        }

        public IActionResult BusinessAndOffice()
        {
            ViewData["username"] = Request.Cookies["username"];
            ViewData["firstname"] = Request.Cookies["firstname"];
            string sessionid = Request.Cookies["sessionId"];
            ViewData["sessionId"] = sessionid;
            string customerId = Request.Cookies["customerId"];
            ViewData["customerid"] = customerId;
            List<ShoppingCartItem> shoppingcart = db.ShoppingCartItem.Where(x => x.ShoppingCartId == customerId).ToList();
            List<ShoppingCartItem> shoppingcartNull = db.ShoppingCartItem.Where(x => x.ShoppingCartId == "0").ToList();
            if (sessionid != null)
            {
                ViewData["cartcount"] = shoppingcart.Count;
            }
            else
            {
                ViewData["cartcount"] = shoppingcartNull.Count;
            }
            List<Products> product = db.Products.Where(p => (p.ProductCategory == "BusinessAndOffice")).ToList();
            ViewData["product"] = product;

            ViewData["firstname"] = Request.Cookies["firstname"];
            ViewData["sessionId"] = Request.Cookies["sessionId"];
            return View();
        }
        public IActionResult DesignAndIllustration()
        {
            ViewData["username"] = Request.Cookies["username"];
            ViewData["firstname"] = Request.Cookies["firstname"];
            string sessionid = Request.Cookies["sessionId"];
            ViewData["sessionId"] = sessionid;
            string customerId = Request.Cookies["customerId"];
            ViewData["customerid"] = customerId;
            List<ShoppingCartItem> shoppingcart = db.ShoppingCartItem.Where(x => x.ShoppingCartId == customerId).ToList();
            List<ShoppingCartItem> shoppingcartNull = db.ShoppingCartItem.Where(x => x.ShoppingCartId == "0").ToList();
            if (sessionid != null)
            {
                ViewData["cartcount"] = shoppingcart.Count;
            }
            else
            {
                ViewData["cartcount"] = shoppingcartNull.Count;
            }
            List<Products> product = db.Products.Where(p => (p.ProductCategory == "DesignAndIllustration")).ToList();
            ViewData["product"] = product;

            ViewData["firstname"] = Request.Cookies["firstname"];
            ViewData["sessionId"] = Request.Cookies["sessionId"];
            return View();
        }

        public GalleryController(AppDbContext db)
        {
            this.db = db;
        }
        public List<Products> GetProducts(string keyword)
        {
            List<Products> products = db.Products.ToList();
            {
                if (keyword == "" || keyword == null)
                {
                    return db.Products.ToList();
                }

                return db.Products.Where(p =>
                        p.ProductName.ToLower().Contains(keyword.ToLower()) ||
                        p.ProductDescription.ToLower().Contains(keyword.ToLower()))
                    .ToList();
            }
        }

        [HttpPost]
        public IActionResult Search(string keyword = "")
        {
            List<Products> product = GetProducts(keyword);
            ViewBag.keyword = keyword;
            ViewData["product"] = keyword;
            return View("Index");
        }

        //Link to productDetailPage
        public IActionResult ProductDetailPage(int id)
        {
            ViewData["username"] = Request.Cookies["username"];
            ViewData["firstname"] = Request.Cookies["firstname"];
            string sessionid = Request.Cookies["sessionId"];
            ViewData["sessionId"] = sessionid;
            string customerId = Request.Cookies["customerId"];
            ViewData["customerid"] = customerId;
            List<ShoppingCartItem> shoppingcart = db.ShoppingCartItem.Where(x => x.ShoppingCartId == customerId).ToList();
            List<ShoppingCartItem> shoppingcartNull = db.ShoppingCartItem.Where(x => x.ShoppingCartId == "0").ToList();
            if (sessionid != null)
            {
                ViewData["cartcount"] = shoppingcart.Count;
            }
            else
            {
                ViewData["cartcount"] = shoppingcartNull.Count;
            }

            Products product = db.Products.FirstOrDefault(p => p.ProductId == id);
            List<Products> similarProducts = db.Products.Where(p => 
                                               (p.ProductCategory == product.ProductCategory) && (p!=product))
                                                .ToList();
            
            var reviews = db.Reviews.Where(r => r.ProductID == product.ProductId).ToList();
            double averageRating = reviews.Average(r=>r.StarRating);
            ViewData["reviews"] = reviews;
            ViewData["averageRating"] = averageRating;
            ViewData["product"] = product;
            ViewData["similarProducts"] = similarProducts;
            ViewData["firstname"] = Request.Cookies["firstname"];
            ViewData["sessionId"] = Request.Cookies["sessionId"];

            sessionid = Request.Cookies["sessionId"];
            ViewData["sessionId"] = sessionid;
            customerId = Request.Cookies["customerId"];
            ViewData["customerid"] = customerId;
            shoppingcart = db.ShoppingCartItem.Where(x => x.ShoppingCartId == customerId).ToList();
            shoppingcartNull = db.ShoppingCartItem.Where(x => x.ShoppingCartId == "0").ToList();

            if (sessionid != null)
            {
                ViewData["cartcount"] = shoppingcart.Count;
            }
            else
            {
                ViewData["cartcount"] = shoppingcartNull.Count;
            }

            bool boughtThis = false;
            List<Order> customerOrders = db.Order.Where(o => o.CustomerId == customerId).ToList();
            foreach (Order order in customerOrders) 
            {
                if (order.OrderDetails.Any(o => o.ProductId == id)) 
                {
                    boughtThis = true;
                    break;
                }
            }
            ViewData["boughtThis"] = boughtThis;

            bool reviewedThis = db.Order.Any(o => o.CustomerId == customerId && o.OrderDetails.Any(o => o.reviewed != true && o.ProductId == id));
            ViewData["reviewedThis"] = !reviewedThis;

            return View();

        }

        public IActionResult RemoveReview(int id)
        {
            string customerid = Request.Cookies["customerId"];
            ViewData["customerid"] = customerid;
            string sessionid = Request.Cookies["sessionId"];
            if (sessionid == null)
            {
                customerid = "0";
            }
            var reviewselected = db.Reviews.FirstOrDefault(r => r.ProductID == id && r.CustomerId == customerid);
            if (reviewselected != null)
            {
                db.Reviews.Remove(reviewselected);

Team8CA/Controllers/OrderHistoryController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Team8CA.DataAccess;
using Team8CA.Models;


namespace Team8CA.Controllers
{
    public class OrderHistoryController : Controller
    {


        private readonly AppDbContext db;
        private readonly ShoppingCart shoppingcart;


        public OrderHistoryController(AppDbContext db, ShoppingCart shoppingcart)
        {
            this.db = db;
            this.shoppingcart = shoppingcart;
        }

        public IActionResult Index()
        {
            string customerId = Request.Cookies["customerId"];
            List<Order> orders = db.Order.Where(o => o.CustomerId == customerId).ToList();

            ViewData["order"] = orders;

            ViewData["firstname"] = Request.Cookies["firstname"];
            string sessionid = Request.Cookies["sessionId"];
            ViewData["sessionId"] = sessionid;

            ViewData["customerid"] = customerId;
            List<ShoppingCartItem> shoppingcart = db.ShoppingCartItem.Where(x => x.ShoppingCartId == customerId).ToList();
            List<ShoppingCartItem> shoppingcartNull = db.ShoppingCartItem.Where(x => x.ShoppingCartId == "0").ToList();
            if (sessionid != null)
            {
                ViewData["cartcount"] = shoppingcart.Count;
            }
            else
            {
                ViewData["cartcount"] = shoppingcartNull.Count;
            }
            return View();
        }
        public IActionResult RecentOrder(int orderId)
        {
            Order order = db.Order.First(x => x.OrderId == orderId);
            order.OrderDetails = db.OrderDetails.Where(x => x.OrderId == orderId).ToList();
            foreach (var o in order.OrderDetails)
            {
                o.ActivationCodes = db.ActivationCodes.Where(x => x.OrderId == orderId).ToList();
            }

            string customerId = Request.Cookies["customerId"];
            List<Order> orders = db.Order.Where(o => o.CustomerId == customerId).ToList();

            ViewData["order"] = orders;

            ViewData["firstname"] = Request.Cookies["firstname"];
            string sessionid = Request.Cookies["sessionId"];
            ViewData["sessionId"] = sessionid;
            ViewData["customerid"] = customerId;
            List<Review> cutsomerReviews = db.Reviews.Where(r => r.CustomerId == customerId).ToList();
            List<ShoppingCartItem> shoppingcart = db.ShoppingCartItem.Where(x => x.ShoppingCartId == customerId).ToList();
            List<ShoppingCartItem> shoppingcartNull = db.ShoppingCartItem.Where(x => x.ShoppingCartId == "0").ToList();
            if (sessionid != null)
            {
                ViewData["cartcount"] = shoppingcart.Count;
            }
            else
            {
                ViewData["cartcount"] = shoppingcartNull.Count;
            }

            List<Review> customerReviews = db.Reviews.Where(r => r.CustomerId == customerId).ToList();
            ViewData["customerReviews"] = customerReviews;

            return View(order);
        }
    }
}

Team8CA/Views/Cart/Checkout.cshtml
@model Order
@*@using Microsoft.Extensions.Options*@

@*@inject IOptions<Team8CA.Services.StripeSettings> Stripe*@

@*@{
    ViewData["Title"] = "ShoppingCart";
    //List<ShoppingCartItem> shoppingcartitems = (List<ShoppingCartItem>)ViewData["shoppingcartitems"];
}*@

@*<form asp-action="Checkout" method="Post" role="form">*@
    <br />
    <div class="backgroundWhiteBorder">
        <div class="container">
            <div class="card">
                <div class="card-header bg-dark text-light ml-0 row container">
                    <div class="col-6">
                        <i class="fa fa-shopping-cart"></i> &nbsp;
                        Order Summary
                    </div>
                    <div class="col-6 text-right">
                        <a asp-area="" asp-controller="Cart" asp-action="Index" class="btn btn-outline-info btn-sm">Back to cart</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="container rounded p-2">
                        <div class="row">
                            <div class="col-12 col-lg-6 pb-4">
                                <div class="row">
                                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                                        <span class="text-info">Billing Address:</span>
                                    </h4>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Name</label>
                                    </div>
                                    <div class="col-9">
                                        @*<input asp-for="Name" type="text" class="form-control" />*@
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Phone</label>
                                    </div>
                                    <div class="col-9">
                                        @*<input asp-for="PhoneNumber" type="text" class="form-control" />*@
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Street Address</label>
                                    </div>
                                    <div class="col-9">
                                        @*<input asp-for="StreetAddress" type="text" class="form-control" />*@
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>City</label>
                                    </div>
                                    <div class="col-9">
                                        @*<input asp-for="City" type="text" class="form-control" />*@
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>State</label>
                                    </div>
                                    <div class="col-9">
                                        @*<input asp-for="State" type="text" class="form-control" />*@
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Postal Code</label>
                                    </div>
                                    <div class="col-9">
                                        @*<input asp-for="PostalCode" type="text" class="form-control" />*@
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-lg-5 offset-lg-1">
                                <h4 class="d-flex justify-content-between align-items-center mb-3">
                                    <span class="text-info">Order Summary:</span>
                                </h4>
                                <ul class="list-group mb-3">
                                    @*@{ double subtotal = 0;
                                        double total = 0;}*@
                                    @*@foreach (ShoppingCartItem cartitem in shoppingcartitems)
                                    {
                                        <li class="list-group-item d-flex justify-content-between">
                                            <div>
                                                <h6 class="my-0">@cartitem.Products.ProductName</h6>
                                                <small class="text-muted">Price: $@cartitem.Products.ProductPrice</small>
                                                <small class="text-muted">Quantity: @cartitem.Quantity</small>
                                            </div>
                                            @{ subtotal = @cartitem.Products.ProductPrice * @cartitem.Quantity;
                                                total += subtotal;}
                                            <span class="text-muted">$ @subtotal</span>
                                        </li>
                                    }*@
                                    @*<li class="list-group-item d-flex justify-content-between bg-light">
                                        <small class="text-info">Total ($)</small>
                                        <strong class="text-info">$@total</strong>
                                    </li>*@
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-12 col-md-8 pt-2">
                            @*<p style="color:maroon; font-size:14px;">Estimate Arrival Date: @DateTime.Now.AddDays(0).ToShortDateString() - @DateTime.Now.AddDays(3).ToShortDateString()</p>*@
                        </div>
                        <div class="col-12 col-md-4">

                            @*@{
                                var OrderTotalForStripe = @total * 100;
                            }*@
                            @*<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                        data-key="@Stripe.Value.PublishableKey"
                                        data-amount="@OrderTotalForStripe"
                                        data-name="Bulky Book"
                                        data-label="Place Order"
                                        data-description="Get Books, For Less"
                                        data-locale="auto"
                                        data-allow-remember-me="false"
                                        data-image="https://stripe.com/img/documentation/checkout/marketplace.png">
                                </script>
                                <script>
                                    document.getElementsByClassName("stripe-button-el")[0].style.display = 'none';
                                </script>*@
                            <input type="submit" value="Place Order" class="btn btn-success form-control"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@*</form>*@

Team8CA/Views/Cart/CheckoutComplete.cshtml
<div class="text-center">@ViewBag.CheckoutCompleteMessage</div><br />
<div class="text-center"><a type="button" class="btn btn-primary view" asp-controller="OrderHistory" asp-action="Index">View Purchases</a></div><br />
<div class="text-center"><a type="text/html" class="text" asp-controller="Gallery" asp-action="Index">Continue Shopping</a></div>

Team8CA/Views/Cart/Index.cshtml
@using Microsoft.Extensions.Options

@inject IOptions<Team8CA.Services.StripeSettings> Stripe

@{
    ViewData["Title"] = "ShoppingCart";
    List<ShoppingCartItem> shoppingcartitems = (List<ShoppingCartItem>)ViewData["shoppingcartitems"];
    int cartcount = (int)ViewData["cartcount"];
}

<style>
    img.one {
        height: 20%;
        width: 20%;
    }
</style>

<br />
@if (cartcount > 0)
{
    <div class="backgroundWhiteBorder">
        <div class="container">
            <div class="card">

                <div class="card-header bg-dark text-light ml-0 row container">
                    <div class="col-6">
                        <i class="fa fa-shopping-cart"></i> &nbsp;
                        Shopping Cart
                    </div>
                    <div class="col-6 text-right">
                        <a asp-area="" asp-controller="Gallery" asp-action="Index" class="btn btn-outline-info btn-sm">Continue Shopping</a>
                    </div>
                </div>
                <div class="card-body">
                    @{double subtotal = 0.00;
                        double total = 0.00;}
                    @foreach (ShoppingCartItem cartitem in shoppingcartitems)
                    {
                        <div class="row">
                            <div class="d-none d-lg-block col-lg-1 text-center py-2">
                                <img src="@cartitem.Products.ProductPic" class="rounded" width="100%" />
                            </div>
                            <div class="col-12 text-sm-center col-lg-5 text-lg-left">
                                <h5><strong>@cartitem.Products.ProductName</strong></h5>
                                <p><small>@cartitem.Products.ProductDescription</small></p>

                            </div>
                            <div class="col-12 text-sm-center col-lg-6 text-lg-right row">
                                <div class="col-2 text-md-right" style="padding-top:5px;">
                                    <h6><strong>$@cartitem.Products.ProductPrice</strong></h6>
                                </div>
                                <div class="col-2 text-md-right" style="padding-top:5px;">
                                    <h6><strong>@cartitem.Quantity pcs</strong></h6>
                                </div>
                                <div class="col-2 col-sm-4 col-lg-3">
                                    <div class="float-left mx-1">
                                        <a asp-area="" asp-controller="Cart" asp-action="AddInCart" asp-route-productid="@cartitem.ProductsId" alt="" class="btn btn-primary">
                                            <i class="fas fa-plus"></i>
                                        </a>
                                    </div>
                                    <div class="float-left mx-1">
                                        <a asp-area="" asp-controller="Cart" asp-action="RemoveFromShoppingCart" asp-route-productid="@cartitem.ProductsId" alt="" class="btn btn-danger">
                                            <i class="fas fa-minus"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-3 text-md-center" style="padding-top:5px;">
                                    @{subtotal = @cartitem.Products.ProductPrice * @cartitem.Quantity;
                                        total += subtotal;}
                                    <h6><strong>$@subtotal</strong></h6>
                                </div>
                                <div class="col-2 col-sm-4 col-lg-2 text-right">
                                    <a asp-area="" asp-controller="Cart" asp-action="RemoveCartRow" asp-route-productid="@cartitem.ProductsId" alt="" class="btn btn-outline-danger">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <hr />

                    }
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-12 col-md-6 offset-md-6 col-lg-4 offset-lg-8 pr-4">
                            <ul class="list-group">
                                <li class="list-group-item d-flex justify-content-between bg-light">
                                    <strong class="text-info"> Grand Total ($)</strong>
                                    <strong class="text-info">$ <span id="txtOrderTotal">@total</span></strong>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="card-footer">
                    <div class="card-footer row">

                        <div class="col-sm-12 col-lg-4 col-md-6 offset-lg-8 offset-md-6 ">
                            
                            <form asp-action="Checkout" asp-controller="Cart" method="Post" role="form">
                                @{
                                    var OrderTotalForStripe = @total * 100;
                                }
                                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                        data-key="@Stripe.Value.PublishableKey"
                                        data-amount="@OrderTotalForStripe"
                                        data-name="T8Softwares"
                                        data-label="Place Order"
                                        data-description="Hope you enjoy the purchase!"
                                        data-locale="auto"
                                        data-allow-remember-me="false"
                                        data-image="Images/t8software-04.png" >
                                </script>
                                <script>
                                    document.getElementsByClassName("stripe-button-el")[0].style.display = 'none';
                                </script>
                                <input type="submit" value="Place Order" class="btn btn-success form-control" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div class="text-center">There are no items in the shopping cart.</div><br />
    <div class="text-center"><a type="button" class="btn btn-primary view" asp-controller="Gallery" asp-action="Index">Continue Shopping</a></div>
}